# Generated by Django 4.2.11 on 2024-12-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefighters',
            name='rank',
            field=models.CharField(choices=[('Probationary Firefighter', 'Probationary Firefighter'), ('Firefighter I', 'Firefighter I'), ('Firefighter II', 'Firefighter II'), ('Firefighter III', 'Firefighter III'), ('Driver', 'Driver'), ('Captain', 'Captain'), ('Battalion Chief', 'Battalion Chief')], max_length=150),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fire.firestation'),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True),
        ),
    ]
